### ISSUE TITLE
acn't use UI

### ISSUE THREAD

**Issue by baldy-mikey** [Plachtaa/VALL-E-X#132]
Heya, sorry to bother you. I follow the instructions, but always get stuck when launching UI

I get this error.

I hope you can help?

component_meta.py", line 146, in wrapper
    return fn(self, **kwargs)
TypeError: Audio.__init__() got an unexpected keyword argument 'source'

Rgds
Mike

**Comment by baldy-mikey** [comment]
> I have the same error, please help
> 
> > C:\Users\profi\anaconda3\envs\valle\lib\site-packages\torch\nn\utils\weight_norm.py:30: UserWarning: torch.nn.utils.weight_norm is deprecated in favor of torch.nn.utils.parametrizations.weight_norm.
> > warnings.warn("torch.nn.utils.weight_norm is deprecated in favor of torch.nn.utils.parametrizations.weight_norm.")
> > Traceback (most recent call last):
> > File "c:\ai\VALL-E-X\launch-ui.py", line 629, in 
> > main()
> > File "c:\ai\VALL-E-X\launch-ui.py", line 528, in main
> > upload_audio_prompt = gr.Audio(label='uploaded audio prompt', source='upload', interactive=True)
> > File "C:\Users\profi\anaconda3\envs\valle\lib\site-packages\gradio\component_meta.py", line 146, in wrapper
> > return fn(self, **kwargs)
> > TypeError: Audio.**init**() got an unexpected keyword argument 'source'

I managed to solve and by accident.. i did these installs which solved it for me.
	pip install chardet
	pip install numpy==1.24

**Comment by kumaranjeya** [comment]
Had same issue. Resolved by...

pip uninstall gradio
pip install gradio==3.50.2

**Comment by baldy-mikey** [comment]
i've uninstalled gradio and reinstalled as per above and getting this issue:

site-packages\torch\serialization.py", line 447, in __init__
    super().__init__(torch._C.PyTorchFileReader(name_or_buffer))
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: PytorchStreamReader failed reading zip archive: failed finding central directory


Any help, would be fantastic
Rgds
Mike

**Comment by baldy-mikey** [comment]
> I have the same error, please help
> 
> > C:\Users\profi\anaconda3\envs\valle\lib\site-packages\torch\nn\utils\weight_norm.py:30: UserWarning: torch.nn.utils.weight_norm is deprecated in favor of torch.nn.utils.parametrizations.weight_norm.
> > warnings.warn("torch.nn.utils.weight_norm is deprecated in favor of torch.nn.utils.parametrizations.weight_norm.")
> > Traceback (most recent call last):
> > File "c:\ai\VALL-E-X\launch-ui.py", line 629, in 
> > main()
> > File "c:\ai\VALL-E-X\launch-ui.py", line 528, in main
> > upload_audio_prompt = gr.Audio(label='uploaded audio prompt', source='upload', interactive=True)
> > File "C:\Users\profi\anaconda3\envs\valle\lib\site-packages\gradio\component_meta.py", line 146, in wrapper
> > return fn(self, **kwargs)
> > TypeError: Audio.**init**() got an unexpected keyword argument 'source'

did you manage to fix it? I'm still struggling

**Comment by kumaranjeya** [comment]
> i've uninstalled gradio and reinstalled as per above and getting this issue:
> 
> site-packages\torch\serialization.py", line 447, in **init** super().**init**(torch._C.PyTorchFileReader(name_or_buffer)) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ RuntimeError: PytorchStreamReader failed reading zip archive: failed finding central directory
> 
> Any help, would be fantastic Rgds Mike

I think your Torch installation is corrupted. Try..

pip uninstall torch
pip install torch

**Comment by Charlz91108112** [comment]
Hello everyone, I was able to solve this issue by following the solution by @kumaranjeya . Thank you for the fix. 


> Had same issue. Resolved by...
> 
> pip uninstall gradio pip install gradio==3.50.2

**Comment by baldy-mikey** [comment]
I ended up having to create absolute paths for the json in the generate.py file. And also manually downloading the file and changing the checkpoints part, as it was always trying to download them even though i had already done it ... a bit of a pain, but got it working

**Comment by TGajanan** [comment]
> Had same issue. Resolved by...
> 
> pip uninstall gradio pip install gradio==3.50.2

Thanks, this works for me

**Comment by mlo0352** [comment]
> Had same issue. Resolved by...
> 
> pip uninstall gradio pip install gradio==3.50.2

I was having the same issue as OP when trying to run suno-ai bark, and this solved it. Thanks!
