### ISSUE TITLE
run show Audio.__init__() got an unexpected keyword argument 'source'？

### ISSUE THREAD

**Issue by BoragoCode** [Plachtaa/VALL-E-X#136]
(py310_asrtts) root@iZuf6f62zjps99tce8voxpZ:/opt/wdd/model/VALL-E-X# python launch-ui.py
default encoding is utf-8,file system encoding is utf-8
You are using Python version 3.10.13
/root/anaconda3/envs/py310_asrtts/lib/python3.10/site-packages/whisper/timing.py:57: NumbaDeprecationWarning: The 'nopython' keyword argument was not supplied to the 'numba.jit' decorator. The implicit default value for this argument is currently False, but it will be changed to True in Numba 0.59.0. See https://numba.readthedocs.io/en/stable/reference/deprecation.html#deprecation-of-object-mode-fall-back-behaviour-when-using-jit for details.
  def backtrace(trace: np.ndarray):
Use 16 cpu cores for computing
100%|█████████████████████████████████████| 1.42G/1.42G [02:15<00:00, 11.3MiB/s]
Traceback (most recent call last):
  File "/opt/wdd/model/VALL-E-X/launch-ui.py", line 629, in <module>
    main()
  File "/opt/wdd/model/VALL-E-X/launch-ui.py", line 528, in main
    upload_audio_prompt = gr.Audio(label='uploaded audio prompt', source='upload', interactive=True)
  File "/root/anaconda3/envs/py310_asrtts/lib/python3.10/site-packages/gradio/component_meta.py", line 146, in wrapper
    return fn(self, **kwargs)
TypeError: Audio.__init__() got an unexpected keyword argument 'source'

environment：py31.0

**Comment by Plachtaa** [comment]
#132

**Comment by inikishev** [comment]
it got renamed to sources so rename source to sources
