### ISSUE TITLE
出现这个问题

### ISSUE THREAD

**Issue by 40740** [Plachtaa/VALL-E-X#22]
我有8G的GPU,但是还是出现这样的问题？
`G:\AI\VALL\VALL-E-X-master\myenv\lib\site-packages\whisper\timing.py:58: NumbaDeprecationWarning: The 'nopython' keyword argument was not supplied to the 'numba.jit' decorator. The implicit default value for this argument is currently False, but it will be changed to True in Numba 0.59.0. See https://numba.readthedocs.io/en/stable/reference/deprecation.html#deprecation-of-object-mode-fall-back-behaviour-when-using-jit for details.
  def backtrace(trace: np.ndarray):
Use 8 cpu cores for computing
Traceback (most recent call last):
  File "G:\AI\VALL\VALL-E-X-master\VALL-E-X-master\ui.py", line 84, in <module>
    whisper_model = whisper.load_model("medium").cpu()
  File "G:\AI\VALL\VALL-E-X-master\myenv\lib\site-packages\whisper\__init__.py", line 154, in load_model
    return model.to(device)
  File "G:\AI\VALL\VALL-E-X-master\myenv\lib\site-packages\torch\nn\modules\module.py", line 1145, in to
    return self._apply(convert)
  File "G:\AI\VALL\VALL-E-X-master\myenv\lib\site-packages\torch\nn\modules\module.py", line 797, in _apply
    module._apply(fn)
  File "G:\AI\VALL\VALL-E-X-master\myenv\lib\site-packages\torch\nn\modules\module.py", line 797, in _apply
    module._apply(fn)
  File "G:\AI\VALL\VALL-E-X-master\myenv\lib\site-packages\torch\nn\modules\module.py", line 797, in _apply
    module._apply(fn)
  [Previous line repeated 2 more times]
  File "G:\AI\VALL\VALL-E-X-master\myenv\lib\site-packages\torch\nn\modules\module.py", line 820, in _apply
    param_applied = fn(param)
  File "G:\AI\VALL\VALL-E-X-master\myenv\lib\site-packages\torch\nn\modules\module.py", line 1143, in convert
    return t.to(device, dtype if t.is_floating_point() or t.is_complex() else None, non_blocking)
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 20.00 MiB (GPU 0; 4.00 GiB total capacity; 3.05 GiB already allocated; 0 bytes free; 3.06 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF`

**Comment by ZYFDroid** [comment]
看起来是在加载whisper（另一个ai模型，用于识别声音中的文字）的时候出现了错误。

目前vallex需要输入一段声音，这段声音中的文字内容，以及要合成的文字内容，输出合成的声音。
如果你没有输入原音频中的文字内容，那么就会调用whisper模型自动识别原音频中的文字内容。这将花费额外的显存。

可以尝试手动输入原音频中的文本内容来避免调用whisper

**Comment by 40740** [comment]
感谢哥哥答复，我运行 ui时（python launch-ui.py），没有启动成功就出现这个报错。很奇怪

**Comment by ZYFDroid** [comment]
可以尝试修改源代码，删除加载whisper模型的部分

**Comment by 40740** [comment]
我试试看看~

**Comment by 40740** [comment]
可以了，打开ui了。是whisper和程序强GPU了。去掉whisper就可以
