### ISSUE TITLE
When localhost is not accessible

### ISSUE THREAD

**Issue by prayforsomeone** [Plachtaa/VALL-E-X#26]
Running on local URL:  http://127.0.0.1:7860
Traceback (most recent call last):
  File "C:\VALL-E-X-master\launch-ui.py", line 571, in <module>
    main()
  File "C:\VALL-E-X-master\launch-ui.py", line 564, in main
    app.launch()
  File "C:\Users\***\AppData\Local\Programs\Python\Python311\Lib\site-packages\gradio\blocks.py", line 1974, in launch
    raise ValueError(
ValueError: When localhost is not accessible, a shareable link must be created. Please set share=True or check your proxy settings to allow access to localhost.

请问这个要怎么改？

**Comment by JoonSumisu** [comment]
When localhost is not accessible, a shareable link must be created. Please set share=True or check your proxy settings to allow access to localhost.

希望能描述下你的环境是怎么样的，提示为 请使用share=True 或者检查代理让你能连接到localhost.

**Comment by ZYFDroid** [comment]
Try turn off your proxy software (e.g. v2ray, clash)

**Comment by Accurio** [comment]
If you use a proxy server in Windows, you may need to set `HTTP_PROXY`,  `HTTPS_PROXY` and `NO_PROXY` environment variables.

```Python
import os
from urllib.request import getproxies

proxies = getproxies()
os.environ["http_proxy"]  = proxies["http"]
os.environ["https_proxy"] = proxies["https"]
os.environ["no_proxy"]    = "localhost, 127.0.0.1/8, ::1"
```
