### ISSUE TITLE
报错 Kernel size can't be greater than actual input size

### ISSUE THREAD

**Issue by heiheiheibj** [Plachtaa/VALL-E-X#53]
生成NPZ文件正常，再创建新的语音时，提示
RuntimeError: Calculated padded input size per channel: (6). Kernel size: (7). Kernel size can't be greater than actual input size

谢谢

**Comment by heiheiheibj** [comment]
D:\VALL-E-X\whisper\medium.pt exists, but the SHA256 checksum does not match; re-downloading the file
  warnings.warn(
100%|█████████████████████████████████████| 1.42G/1.42G [05:02<00:00, 5.05MiB/s]
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
Building prefix dict from the default dictionary ...
2023-08-31 02:34:11,911 DEBUG [__init__.py:113] Building prefix dict from the default dictionary ...
Loading model from cache C:\Users\ADMINI~1\AppData\Local\Temp\jieba.cache
2023-08-31 02:34:11,913 DEBUG [__init__.py:132] Loading model from cache C:\Users\ADMINI~1\AppData\Local\Temp\jieba.cache
Loading model cost 0.899 seconds.
2023-08-31 02:34:12,811 DEBUG [__init__.py:164] Loading model cost 0.899 seconds.
Prefix dict has been built successfully.
2023-08-31 02:34:12,813 DEBUG [__init__.py:166] Prefix dict has been built successfully.
2023-08-31 02:36:11,248 INFO [launch-ui.py:327] synthesize text: [ZH]其实那个时候他们就已经很反感这个，这些东西了，他就 已经不想弄了[ZH]
VALL-E EOS [495 -> 496]
Traceback (most recent call last):
  File "D:\ProgramData\Anaconda3\envs\chatgpt6b2\lib\site-packages\gradio\routes.py", line 412, in run_predict
    output = await app.get_blocks().process_api(
  File "D:\ProgramData\Anaconda3\envs\chatgpt6b2\lib\site-packages\gradio\blocks.py", line 1299, in process_api
    result = await self.call_function(
  File "D:\ProgramData\Anaconda3\envs\chatgpt6b2\lib\site-packages\gradio\blocks.py", line 1021, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "D:\ProgramData\Anaconda3\envs\chatgpt6b2\lib\site-packages\anyio\to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "D:\ProgramData\Anaconda3\envs\chatgpt6b2\lib\site-packages\anyio\_backends\_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "D:\ProgramData\Anaconda3\envs\chatgpt6b2\lib\site-packages\anyio\_backends\_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "D:\ProgramData\Anaconda3\envs\chatgpt6b2\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "D:\VALL-E-X\launch-ui.py", line 351, in infer_from_prompt
    samples = vocos.decode(features, bandwidth_id=torch.tensor([2], device=device))
  File "D:\ProgramData\Anaconda3\envs\chatgpt6b2\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "D:\ProgramData\Anaconda3\envs\chatgpt6b2\lib\site-packages\vocos\pretrained.py", line 110, in decode
    x = self.backbone(features_input, **kwargs)
  File "D:\ProgramData\Anaconda3\envs\chatgpt6b2\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "D:\ProgramData\Anaconda3\envs\chatgpt6b2\lib\site-packages\vocos\models.py", line 78, in forward
    x = self.embed(x)
  File "D:\ProgramData\Anaconda3\envs\chatgpt6b2\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "D:\ProgramData\Anaconda3\envs\chatgpt6b2\lib\site-packages\torch\nn\modules\conv.py", line 313, in forward
    return self._conv_forward(input, self.weight, self.bias)
  File "D:\ProgramData\Anaconda3\envs\chatgpt6b2\lib\site-packages\torch\nn\modules\conv.py", line 309, in _conv_forward
    return F.conv1d(input, weight, bias, self.stride,
RuntimeError: Calculated padded input size per channel: (6). Kernel size: (7). Kernel size can't be greater than actual input size

**Comment by Plachtaa** [comment]
请分享一下你的`.npz`文件，我会尝试复现错误并寻找原因

**Comment by heiheiheibj** [comment]
[zzh.zip](https://github.com/Plachtaa/VALL-E-X/files/12479338/zzh.zip)
NPZ文件在这，谢谢。。

**Comment by Plachtaa** [comment]
这个prompt除了效果很差以外并没有其它特别之处，我在本地机器上无法复现你的错误。建议你到huggingface space中尝试使用该prompt并观察结果。

**Comment by heiheiheibj** [comment]
这个音频效果是比较差，从以前视频中截取的。我在其它机器上重装了一下环境，问题解决了，非常感谢。
