### ISSUE TITLE
运行demo的时候报错，这个错不知道怎么解，求助下。

### ISSUE THREAD

**Issue by bieyongdapaodawenzi** [Plachtaa/VALL-E-X#69]
测试代码如下：
~/VALL-E-X# cat test.py
from utils.generation import SAMPLE_RATE, generate_audio, preload_models
from scipy.io.wavfile import write as write_wav
from IPython.display import Audio
preload_models()
text_prompt = """
Hello, my name is Nose. And uh, and I like hamburger. Hahaha... But I also have other interests such as playing tactic toast.
"""
audio_array = generate_audio(text_prompt)
write_wav("vallex_generation.wav", SAMPLE_RATE, audio_array)
Audio(audio_array, rate=SAMPLE_RATE)

报错信息如下：
/VALL-E-X# python3 test.py
Traceback (most recent call last):
  File "test.py", line 1, in <module>
    from utils.generation import SAMPLE_RATE, generate_audio, preload_models
  File "/root/VALL-E-X/utils/generation.py", line 4, in <module>
    from vocos import Vocos
  File "/root/miniconda3/lib/python3.8/site-packages/vocos/__init__.py", line 1, in <module>
    from vocos.pretrained import Vocos
  File "/root/miniconda3/lib/python3.8/site-packages/vocos/pretrained.py", line 7, in <module>
    from vocos.feature_extractors import FeatureExtractor, EncodecFeatures
  File "/root/miniconda3/lib/python3.8/site-packages/vocos/feature_extractors.py", line 8, in <module>
    from vocos.modules import safe_log
  File "/root/miniconda3/lib/python3.8/site-packages/vocos/modules.py", line 89, in <module>
    class ResBlock1(nn.Module):
  File "/root/miniconda3/lib/python3.8/site-packages/vocos/modules.py", line 109, in ResBlock1
    dilation: tuple[int] = (1, 3, 5),
TypeError: 'type' object is not subscriptable

通过这个错误提示，我有点懵，不知道咋解，求助下。谢谢。

**Comment by bieyongdapaodawenzi** [comment]
python必须要大于3.8，我升级到3.10就好了。哎...
