### ISSUE TITLE
Request for detailed error logging

### ISSUE THREAD

**Issue by neruthes** [Plachtaa/VALL-E-X#72]
The webpage sometimes report a clueless error without giving any detail in the web console or the Python process stdout.

I cannot even file a proper bug report now. For the sake of troubleshooting, more details for errors are necessary.

For my current situation, I have attached 2 prompts below for a possible diagnosis.

https://minio.neruthes.xyz/oss/keep/tts/ne4-en.npz--497c87272d54025a6ee6bd910ac00ff8.npz

https://minio.neruthes.xyz/oss/keep/tts/ne5-zh.npz--e9bfa9f90806015d8a886c89d250174b.npz

**Comment by Plachtaa** [comment]
This is because the audio you used to make the prompt is too long, which is unable to be handled by the model. See https://github.com/Plachtaa/VALL-E-X#why-the-model-fails-to-generate-long-text for detailed explanation. 
If the AR model predicted only a EOS token, it cannot be decoded by the audio codec. The full error log is as follows:
```
VALL-E EOS [3700 -> 3701]
Traceback (most recent call last):
  File "/home/user/.pyenv/versions/3.10.13/lib/python3.10/site-packages/gradio/routes.py", line 442, in run_predict
    output = await app.get_blocks().process_api(
  File "/home/user/.pyenv/versions/3.10.13/lib/python3.10/site-packages/gradio/blocks.py", line 1392, in process_api
    result = await self.call_function(
  File "/home/user/.pyenv/versions/3.10.13/lib/python3.10/site-packages/gradio/blocks.py", line 1097, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "/home/user/.pyenv/versions/3.10.13/lib/python3.10/site-packages/anyio/to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/home/user/.pyenv/versions/3.10.13/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "/home/user/.pyenv/versions/3.10.13/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "/home/user/.pyenv/versions/3.10.13/lib/python3.10/site-packages/gradio/utils.py", line 703, in wrapper
    response = f(*args, **kwargs)
  File "/home/user/.pyenv/versions/3.10.13/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/home/user/app/app.py", line 325, in infer_from_prompt
    samples = vocos.decode(features, bandwidth_id=torch.tensor([2], device=device))
  File "/home/user/.pyenv/versions/3.10.13/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/home/user/.pyenv/versions/3.10.13/lib/python3.10/site-packages/vocos/pretrained.py", line 110, in decode
    x = self.backbone(features_input, **kwargs)
  File "/home/user/.pyenv/versions/3.10.13/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/user/.pyenv/versions/3.10.13/lib/python3.10/site-packages/vocos/models.py", line 78, in forward
    x = self.embed(x)
  File "/home/user/.pyenv/versions/3.10.13/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/user/.pyenv/versions/3.10.13/lib/python3.10/site-packages/torch/nn/modules/conv.py", line 313, in forward
    return self._conv_forward(input, self.weight, self.bias)
  File "/home/user/.pyenv/versions/3.10.13/lib/python3.10/site-packages/torch/nn/modules/conv.py", line 309, in _conv_forward
    return F.conv1d(input, weight, bias, self.stride,
RuntimeError: Calculated padded input size per channel: (6). Kernel size: (7). Kernel size can't be greater than actual input size
```

**Comment by neruthes** [comment]
Thank you. I will try using a shorter voice signature sample. BTW is there any specific magic number that you can suggest? For example, no more than X words and/or no more than Y seconds.

**Comment by Plachtaa** [comment]
personally I recommend 2~6 seconds
